project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"
    - "Notebook_*.py"

website:
  title: "Neural-GNN"
  navbar:
    tools:
      - icon: github
        href: https://github.com/saalfeldlab/neural-gnn
  page-footer: "Copyright 2025, Cédric Allier, Michael Innerberger, Stephan Saalfeld"

execute:
  enabled: false

format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: styles.css
    toc: true
